### ISSUE TITLE
404 Not Found on SVG

### ISSUE THREAD

**Issue by tomkcey** [vankop/jsoneditor-react#12] opened 2019-07-18 19:02 UTC
Greetings,

I'm wondering; I'm using the jsoneditor-react, included a svg-loader in my webpack configurations since it was giving me an error to this effect, but now I'm getting this error here.
`GET http://localhost:8080/%3Csvg%20xmlns:dc=%22http://purl.org/dc/elements/1.1/%22%20xmlns:cc=%22http://creativecommons.org/ns 404 (Not Found)`

Does anyone have any idea why it's giving me this GET error? Do I really have to have a img folder in which I'll put the jsoneditor svg files?

Any help is greatly appreciated.

Thomas

**Comment by vankop** [comment] 2019-07-18 19:59
Hi! Could you create a small repo to reproduce your issue. `package.json`, webpack config and example of usage jsoneditor will be enough

**Comment by tomkcey** [comment] 2019-07-18 20:24
Thanks for looking into this. Here it is: [](https://github.com/tomkcey/demo_jsoneditor_react)

**Comment by vankop** [comment] 2019-07-18 20:58
Hm, looks like you better to ask question about svg-inline-loader [here](https://github.com/webpack-contrib/svg-inline-loader). For fast solution I can suggest to use `url-loader` works for me https://webpack.js.org/loaders/url-loader/

**Comment by vankop** [comment] 2019-07-18 21:01
Oh I realised why it does not work with inline loader. Svg is requested like this
`background: transparent url("img/jsoneditor-icons.svg");`

So inline svg is requested from network

**Comment by vankop** [comment] 2019-07-18 21:04
If you still want to use `svg-inline-loader` in your project, I suggest to change config like this:
```
{
  test: /\.svg$/,
  exclude: 'jsoneditor-react',
  use: ['svg-inline-loader']
},
{
  test: /\.svg$/,
  use: ['url-loader']
}
```

**Comment by tomkcey** [comment] 2019-07-18 21:11
Thank you!
This here worked:
`{
                test: /\.svg$/,
                exclude: /jsoneditor-react/,
                use: ['svg-inline-loader']
            },
            {
                test: /\.svg$/,
                use: ['url-loader']
}`

**Comment by vankop** [comment] 2019-07-18 21:20
https://daringfireball.net/projects/markdown/syntax fyi @tomkcey 

Closing this

**Closed by vankop** 2019-07-18 21:20 UTC
